### ISSUE TITLE
Comment highlighting is almost invisible

### ISSUE THREAD

**Issue by chrishiam** [playrust/CSS-Stylesheet#5]
@DERPYBASTARD can you explain?

**Comment by DERPYBASTARD** [comment]
Forgot to mention it was for RES. RES users can click on a comment or use keyboard navigation (J for next item, K for previous item I believe) to highlight it. This highlighting is present, but the color that jumps in when you highlight an item is nearly the same as the background color.

**Comment by chrishiam** [comment]
Gotcha

**Comment by DERPYBASTARD** [comment]
Fixed it
